### ISSUE TITLE
ValueError: The input audio cannot be decoded. See nested exception for details.

### ISSUE THREAD

**Issue by yaodada1** [facebookresearch/seamless_communication#133]

**Comment by debrupf2946** [comment]
please, provide the full error message and details so that the error can be reproduced and worked on

**Comment by cndn** [comment]
Full error message will help as @debrupf2946 mentioned, also you could compare your usage with this file which we also use for Huggingface space demo https://github.com/facebookresearch/seamless_communication/blob/main/demo/app.py

**Comment by Juhong-Namgung** [comment]
I got the same error.
I run Huggingface space demo locally not using gradio.[https://github.com/facebookresearch/seamless_communication/blob/main/demo/app.py](https://github.com/facebookresearch/seamless_communication/blob/main/demo/app.py)
```
import torch
import torchaudio
from huggingface_hub import hf_hub_download
from seamless_communication.models.inference.translator import Translator

# Download sample input audio files
filenames = ["assets/sample_input.mp3", "assets/sample_input_2.mp3"]
for filename in filenames:
    hf_hub_download(
        repo_id="facebook/seamless_m4t",
        repo_type="space",
        filename=filename,
        local_dir=".",
    )

AUDIO_SAMPLE_RATE = 16000.0
MAX_INPUT_AUDIO_LENGTH = 60  # in seconds
DEFAULT_TARGET_LANGUAGE = "French"

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

translator = Translator(
    model_name_or_card="seamlessM4T_large",
    vocoder_name_or_card="vocoder_36langs",
    device=device,
    dtype=torch.float16 if "cuda" in device.type else torch.float32,
)

# input audio file path
input_audio_file = "./assets/sample_input.mp3"

# preprocessing for S2ST
arr, org_sr = torchaudio.load(input_audio_file)
new_arr = torchaudio.functional.resample(
    arr, orig_freq=org_sr, new_freq=AUDIO_SAMPLE_RATE
)
max_length = int(MAX_INPUT_AUDIO_LENGTH * AUDIO_SAMPLE_RATE)
if new_arr.shape[1] > max_length:
    new_arr = new_arr[:, :max_length]

torchaudio.save(input_audio_file, new_arr, sample_rate=int(AUDIO_SAMPLE_RATE))

# predict
translated_text, wav, sr = translator.predict(
	input=input_audio_file,
	task_str="S2ST",
	tgt_lang="kor",
	src_lang=None,
	ngram_filtering=True,
)

```

and Error:
```
ValueError: File contains data in an unknown format.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 313, in <module>
    translated_text, wav, sr = translator.predict(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/seamless_communication/models/inference/translator.py", line 207, in predict
    decoded_audio = self.decode_audio(block)
ValueError: The input audio cannot be decoded. See nested exception for details.
```

**Comment by chenxwh** [comment]
I am seeing the same issue, any update on this?

**Comment by pavan-web-dev** [comment]
@Juhong-Namgung The error indicates that mp3 is not a supported input type. The Gradio Audio component in [https://github.com/facebookresearch/seamless_communication/blob/main/demo/app.py](app.py) automatically converts the mp3 file to a wav file format. 

Try converting the mp3 file into wav file and use that to input to the model.

```from __future__ import annotations

import base64
import json
import logging
import os
import shutil
import subprocess
import tempfile
import warnings
from io import BytesIO
from pathlib import Path

import numpy as np
from ffmpy import FFmpeg, FFprobe, FFRuntimeError
with warnings.catch_warnings():
    warnings.simplefilter("ignore")  # Ignore pydub warning if ffmpeg is not installed
    from pydub import AudioSegment

# Use your own audio file here
my_audio_file = './inp_pro-trim5.mp3'

audio = AudioSegment.from_file(my_audio_file)
data = np.array(audio.get_array_of_samples())
if audio.channels > 1:
    data = data.reshape(-1, audio.channels)
sample_rate = audio.frame_rate

def convert_to_16_bit_wav(data):
    # Based on: https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.write.html
    warning = "Trying to convert audio automatically from {} to 16-bit int format."
    if data.dtype in [np.float64, np.float32, np.float16]:
        warnings.warn(warning.format(data.dtype))
        data = data / np.abs(data).max()
        data = data * 32767
        data = data.astype(np.int16)
    elif data.dtype == np.int32:
        warnings.warn(warning.format(data.dtype))
        data = data / 65538
        data = data.astype(np.int16)
    elif data.dtype == np.int16:
        pass
    elif data.dtype == np.uint16:
        warnings.warn(warning.format(data.dtype))
        data = data - 32768
        data = data.astype(np.int16)
    elif data.dtype == np.uint8:
        warnings.warn(warning.format(data.dtype))
        data = data * 257 - 32768
        data = data.astype(np.int16)
    else:
        raise ValueError(
            "Audio data cannot be converted automatically from "
            f"{data.dtype} to 16-bit int format."
        )
    return data
 
format = "wav"
filename = 'output.wav'
if format == "wav":
    data = convert_to_16_bit_wav(data)
audio = AudioSegment(
    data.tobytes(),
    frame_rate=sample_rate,
    sample_width=data.dtype.itemsize,
    channels=(1 if len(data.shape) == 1 else data.shape[1]),
)
file = audio.export(filename, format=format)
file.close()
```

Then plug this file into your code to get the translator working.
