### ISSUE TITLE
Error with running predict.py

### ISSUE THREAD

**Issue by Jamba777** [facebookresearch/seamless_communication#20]
I have some problem while execute script:

```
❯ python3 predict.py /home/jambo/Downloads/bbb.mp3 s2st ukr --output_path au.mp3 --model_name seamlessM4T_large
INFO:__main__:Running inference on the GPU.
Downloading the checkpoint of the model 'seamlessM4T_large'...
100%|████████████████████████████████████████████████████████████████████████████████| 10.7G/10.7G [31:36<00:00, 6.03MB/s]
Downloading the tokenizer of the model 'seamlessM4T_large'...
100%|████████████████████████████████████████████████████████████████████████████████| 4.93M/4.93M [00:00<00:00, 6.06MB/s]
Downloading the checkpoint of the model 'vocoder_36langs'...
100%|██████████████████████████████████████████████████████████████████████████████████| 160M/160M [00:27<00:00, 6.06MB/s]
Traceback (most recent call last):
  File "/home/jambo/Documents/myown/python/projects/seamless_communication/src/predict.py", line 86, in <module>
    main()
  File "/home/jambo/Documents/myown/python/projects/seamless_communication/src/predict.py", line 67, in main
    translated_text, wav, sr = translator.predict(
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/projects/seamless_communication/src/seamless_communication/models/inference/translator.py", line 209, in predict
    result = self.get_prediction(
  File "/home/jambo/Documents/myown/python/projects/seamless_communication/src/seamless_communication/models/inference/translator.py", line 120, in get_prediction
    return generator(
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/projects/seamless_communication/src/seamless_communication/models/unity/generator.py", line 173, in __call__
    text_output = self.s2t_generator.generate_ex(source_seqs, source_seq_lens)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/fairseq2/generation/text.py", line 155, in generate_ex
    return self._do_generate(source_seqs, source_seq_lens)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/fairseq2/generation/text.py", line 71, in _do_generate
    encoder_output, encoder_padding_mask = self.model.encode(
  File "/home/jambo/Documents/myown/python/projects/seamless_communication/src/seamless_communication/models/unity/model.py", line 191, in encode
    return self.encoder(seqs, padding_mask)  # type: ignore[no-any-return]
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/projects/seamless_communication/src/seamless_communication/models/unity/adaptor_block.py", line 104, in forward
    seqs, padding_mask = self.inner(seqs, padding_mask, layer_output_hook)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/fairseq2/nn/transformer/encoder.py", line 155, in forward
    seqs, padding_mask = layer(seqs, padding_mask)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/fairseq2/models/conformer/block.py", line 124, in forward
    seqs = self._forward_conv(seqs, padding_mask)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/fairseq2/models/conformer/block.py", line 169, in _forward_conv
    seqs = self.conv(seqs, padding_mask)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/fairseq2/models/conformer/convolution.py", line 113, in forward
    seqs = self.pointwise_conv1(seqs)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/jambo/Documents/myown/python/envs/seamless/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size

```

**Comment by cndn** [comment]
Hey @Jamba777 The Translator takes 16khz audio, guess you need resample? I will make it explicit in doc.

**Comment by Jamba777** [comment]
It works, thanks!

**Comment by Incarceronn** [comment]
Hi, I'm still facing this same error, even after using the script below to convert my files to 16khz.

I'm using it for an ASR task:

my conversion script can be found below
```
import os
import torchaudio
resample_rate = 16000
data_dir = "train_audios"
new_dir = "train_audios_16khz"
os.makedirs(new_dir, exist_ok = True)

for fpath in os.listdir(data_dir):
    if fpath.endswith(".mp3"):
        waveform, sample_rate = torchaudio.load(os.path.join(data_dir, fpath))          resampler = torchaudio.transforms.Resample(sample_rate, resample_rate,  dtype=waveform.dtype) 
        resampled_waveform = resampler(waveform)
        torchaudio.save(os.path.join(new_dir, fpath), resampled_waveform,       resample_rate)
    else:
        pass
```

**Comment by Incarceronn** [comment]
okay, not sure what exactly was causing the issue, but it's working now, used librosa instead of torchaudio and saved as .wav instead of .mp3 

Dropping my code here in case it's useful to anyone else :).

```
import os
import torchaudio
import librosa
import soundfile

data_dir = "train_audios"
new_dir = "train_audios_16khz_wav"
os.makedirs(new_dir, exist_ok = True)

for fpath in os.listdir(data_dir):
    if fpath.endswith(".mp3"):
        wav, sr = librosa.load(os.path.join(data_dir, fpath), sr = 16000)
        soundfile.write(os.path.join(new_dir, fpath.split('.')[0] + '.wav') ,   wav, sr)
    else:
        pass
```
