### ISSUE TITLE
How to run demo?

### ISSUE THREAD

**Issue by comerc** [facebookresearch/seamless_communication#218]
UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/code/seamless_communication/demo/app.py", line 565, in <module>
    input_audio_mic = gr.Audio(
  File "/myvenv/lib/python3.9/site-packages/gradio/component_meta.py", line 152, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

**Comment by Czj1997-02** [comment]
gradio库的 Audio 方法接收了一个无关参数'source'， 我试着注释掉了，好像不影响使用

**Comment by comerc** [comment]
replace to sources

**Comment by Czj1997-02** [comment]
you can try my project https://github.com/Czj1997-02/SeamlessM4TApp

**Comment by z0rats** [comment]
https://github.com/facebookresearch/seamless_communication/issues/218#issuecomment-1825937068

Solved replacing `source` to `sources` on lines 568 & 574 `app.py`
