### ISSUE TITLE
vocoder-related error message

### ISSUE THREAD

**Issue by martinshkreli** [facebookresearch/seamless_communication#265]
(wslenv) martin@Desktop:/mnt/c/users/shkre/code/seamless/seamless_communication/src/seamless_communication$ python cli/expressivity/evaluate/pretssel_inference.py test.tsv --gated-model-dir /home/martin/.cache/huggingface/hub --task s2st --tgt_lang spa
Traceback (most recent call last):
  File "/mnt/c/users/shkre/code/seamless/wslenv/lib/python3.8/site-packages/seamless_communication-1.0.0-py3.8.egg/seamless_communication/models/unity/loader.py", line 463, in __call__
    gcmvn_stats: Dict[str, List[float]] = card.field("gcmvn_stats").as_(dict)
  File "/mnt/c/users/shkre/code/seamless/wslenv/lib/python3.8/site-packages/fairseq2-0.2.0-py3.8.egg/fairseq2/assets/card.py", line 184, in as_
    value = self.card._get_field_value(self.card.name, self.path)
  File "/mnt/c/users/shkre/code/seamless/wslenv/lib/python3.8/site-packages/fairseq2-0.2.0-py3.8.egg/fairseq2/assets/card.py", line 110, in _get_field_value
    raise AssetCardFieldNotFoundError(
fairseq2.assets.card.AssetCardFieldNotFoundError: The asset card 'vocoder_v2' must have a field named 'gcmvn_stats'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli/expressivity/evaluate/pretssel_inference.py", line 302, in <module>
    main()
  File "cli/expressivity/evaluate/pretssel_inference.py", line 160, in main
    _gcmvn_mean, _gcmvn_std = load_gcmvn_stats(args.vocoder_name)
  File "/mnt/c/users/shkre/code/seamless/wslenv/lib/python3.8/site-packages/seamless_communication-1.0.0-py3.8.egg/seamless_communication/models/unity/loader.py", line 466, in __call__
    gcmvn_stats = model_override["gcmvn_stats"]
KeyError: 'gcmvn_stats'

**Comment by martinshkreli** [comment]
i believe this was related to using python3.8
