### ISSUE TITLE
Chckpoint error during finetuning

### ISSUE THREAD

**Issue by zouberou-sayibou** [facebookresearch/seamless_communication#289]
(base) zouberou@ZOUBE-XPS:/mnt/c/Users/zouby/CompScience/seamless_communication/src/seamless_communication$ python cli/m4t/finetune/finetune.py --train_dataset=jambo_try/train_manifest.json --eval_dataset=jambo_try/validation_manifest.json --save_model_to=jambo_try --mode=SPEECH_TO_SPEECH --model_name=seamlessM4T_large
2023-12-20 02:55:30,266 ERROR -- seamless_communication.cli.m4t.finetune.dist_utils.3483: Cannot init disributed context, as environment varaibles are not set.
Using the cached tokenizer of seamlessM4T_large. Set `force` to `True` to download again.
2023-12-20 02:55:30,422 INFO -- finetune.3483: Finetune params: FinetuneParams(save_model_path=PosixPath('jambo_try'), finetune_mode=<FinetuneMode.SPEECH_TO_SPEECH: 'SPEECH_TO_SPEECH'>, max_epochs=10, label_smoothing=0.2, warmup_steps=100, log_steps=10, eval_steps=50, patience=3, learning_rate=1e-07, train_batch_size=5, eval_batch_size=5, device=device(type='cuda'))       
Using the cached checkpoint of seamlessM4T_large. Set `force` to `True` to download again.
Traceback (most recent call last):
  File "/home/zouberou/miniforge3/lib/python3.10/site-packages/fairseq2/models/utils/generic_loaders.py", line 239, in __call__
    checkpoint = load_checkpoint(
  File "/home/zouberou/miniforge3/lib/python3.10/site-packages/fairseq2/models/utils/checkpoint.py", line 63, in load_checkpoint
    checkpoint: Mapping[str, Any] = torch.load(
  File "/home/zouberou/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/zouberou/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zouberou/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/home/zouberou/.cache/fairseq2/assets/43b8b74ddb6b78486fb47754'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/zouby/CompScience/seamless_communication/src/seamless_communication/cli/m4t/finetune/finetune.py", line 183, in <module>
    main()
  File "/mnt/c/Users/zouby/CompScience/seamless_communication/src/seamless_communication/cli/m4t/finetune/finetune.py", line 145, in main
    model: UnitYModel = load_unity_model(
  File "/home/zouberou/miniforge3/lib/python3.10/site-packages/fairseq2/models/utils/generic_loaders.py", line 246, in __call__
    raise AssetError(
fairseq2.assets.error.AssetError: The checkpoint of seamlessM4T_large cannot be loaded. See nested exception for details.

**Comment by cbalioglu** [comment]
Hi @zouberou-sayibou, do you mind listing the content of the `'/home/zouberou/.cache/fairseq2/assets/43b8b74ddb6b78486fb47754` directory? Are there any files in it?

**Comment by Alexander4127** [comment]
> Hi @zouberou-sayibou, do you mind listing the content of the `'/home/zouberou/.cache/fairseq2/assets/43b8b74ddb6b78486fb47754` directory? Are there any files in it?

Hello! I have faced the same problem, and this directory is empty.

**Comment by spun-jemima** [comment]
I had the same issue but for the SONAR model - I think because I cancelled the job before the models were downloaded properly (see description https://github.com/facebookresearch/SONAR?tab=readme-ov-file#usage ). 
I ran `rm -r ~/.cache/fairseq2/` to clear the dir and ran my script again, worked fine. The models just might take a while to download.

**Comment by WandererGuy** [comment]
FYI, OP's error have ```IsADirectoryError: [Errno 21] Is a directory: '/home/zouberou/.cache/fairseq2/assets/43b8b74ddb6b78486fb47754'```
, just clear the directory by : ```rm -r /home/zouberou/.cache/fairseq2/assets/43b8b74ddb6b78486fb47754``` , then the checkpoint will be downloaded again
