### ISSUE TITLE
AttributeError: 'torch.dtype' object has no attribute 'vocab_info'

### ISSUE THREAD

**Issue by bk111** [facebookresearch/seamless_communication#319]
import torch
from seamless_communication.inference import Translator

# Initialize a Translator object with a multitask model, vocoder on the GPU.*
translator = Translator(
    "seamlessM4T_v2_large",
    "vocoder_v2",
    torch.device("cuda:0"),
    torch.float16,
)

translated_text, _, _ = translator.predict(
    "./input_s2tt.wav",
    "s2tt",
    tgt_lang="eng"
                )
print(translated_text)

-----------------------------------------------------
 python s2tt1.py
Using the cached tokenizer of seamlessM4T_v2_large. Set `force` to `True` to download again.
Using the cached tokenizer of seamlessM4T_v2_large. Set `force` to `True` to download again.
Traceback (most recent call last):
  File "/opt/seamless_communication/demo/m4tv2/s2tt1.py", line 9, in <module>
    translator = Translator(
  File "/usr/local/lib/python3.10/dist-packages/seamless_communication/inference/translator.py", line 145, in __init__
    pad_value=self.text_tokenizer.vocab_info.pad_idx or 0, pad_to_multiple=2
**AttributeError: 'torch.dtype' object has no attribute 'vocab_info'**

**Comment by mavlyutovr** [comment]
Try: 

```
translator = Translator(
"seamlessM4T_v2_large",
"vocoder_v2",
device=torch.device("cuda:0"),
dtype=torch.float16,
)


```

**Comment by bk111** [comment]
after updated as your code. It looks like it needs more gpu memory. I have  a 10G N gpu. What is the smallest amount for audio to text demo on local PC?

**Comment by mavlyutovr** [comment]
16G GPUs should be enough
