### ISSUE TITLE
sos!!!  fairseq2.assets.download_manager.AssetDownloadError: The download of the tokenizer of mintox has failed. See nested exception for details.

### ISSUE THREAD

**Issue by caiji2019-cai** [facebookresearch/seamless_communication#336]
sos!!! fairseq2.assets.download_manager.AssetDownloadError: The download of the tokenizer of mintox has failed. See nested exception for details.
can you help me?

**Comment by antoine-tran** [comment]
@caiji2019-cai : Could you please show the errors you got ?

**Comment by caiji2019-cai** [comment]
i try ping ，but it error。i think i put tokenizer.model on google driver is true, but it can not download the shared file, maybe my net caused it . src/.../cards/mintox.yaml sp_model: https://drive.google.com/ucexport=download&id=14CDVRc6X9M_PrT0Yym9e3pw2FMjOfb_o

**Comment by caiji2019-cai** [comment]
Downloading the tokenizer of mintox...
This step reports an error

**Comment by caiji2019-cai** [comment]
Downloading the tokenizer of mintox...
Traceback (most recent call last):
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/site-packages/fairseq2/assets/download_manager.py", line 379, in _download_asset
    response = cleanup_stack.enter_context(urlopen(request))
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 73, in <module>
    translator = Translator(
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/site-packages/seamless_communication/inference/translator.py", line 130, in __init__
    self.bad_word_checker = load_etox_bad_word_checker("mintox")
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/site-packages/seamless_communication/toxicity/etox_bad_word_checker.py", line 183, in __call__
    sp_pathname = self.download_manager.download_tokenizer(sp_uri, card.name)
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/site-packages/fairseq2/assets/download_manager.py", line 150, in download_tokenizer
    return op.run()
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/site-packages/fairseq2/assets/download_manager.py", line 207, in run
    self._download_asset()
  File "/data/soft/anaconda3/envs/seamless/lib/python3.8/site-packages/fairseq2/assets/download_manager.py", line 381, in _download_asset
    raise AssetDownloadError(
fairseq2.assets.download_manager.AssetDownloadError: The download of the tokenizer of mintox has failed. See nested exception for details.
(seamless)

**Comment by zouhuigang** [comment]
Downloading the tokenizer of seamlessM4T_v2_large...
Traceback (most recent call last):
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/fairseq2/assets/download_manager.py", line 379, in _download_asset
    response = cleanup_stack.enter_context(urlopen(request))
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fscut/seamless-m4t-v2-large/mainv2.py", line 45, in <module>
    translator = Translator(
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/seamless_communication/inference/translator.py", line 113, in __init__
    self.model = load_unity_model(model_name_or_card, device=device, dtype=dtype)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/fairseq2/models/utils/generic_loaders.py", line 257, in __call__
    model = self.model_factory(config, device=Device("meta"), dtype=dtype)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/seamless_communication/models/unity/builder.py", line 517, in create_unity_model
    return unity_builder.build_model()
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/seamless_communication/models/unity/builder.py", line 324, in build_model
    t2u_model = self.t2u_builder.build_model()
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/seamless_communication/models/unity/t2u_builder.py", line 496, in build_model
    decoder_frontend = self.build_decoder_frontend(embed_unit)
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/seamless_communication/models/unity/t2u_builder.py", line 601, in build_decoder_frontend
    nllb_tokenizer = NllbTokenizerLoader(asset_store, download_manager)(
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/fairseq2/models/utils/generic_loaders.py", line 344, in __call__
    path = self.download_manager.download_tokenizer(
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/fairseq2/assets/download_manager.py", line 150, in download_tokenizer
    return op.run()
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/fairseq2/assets/download_manager.py", line 207, in run
    self._download_asset()
  File "/home/fscut/anaconda3/envs/ss/lib/python3.10/site-packages/fairseq2/assets/download_manager.py", line 381, in _download_asset
    raise AssetDownloadError(
fairseq2.assets.download_manager.AssetDownloadError: The download of the tokenizer of seamlessM4T_v2_large has failed. See nested exception for details.

**Comment by jackylee1** [comment]
same

**Comment by liuhao0813** [comment]
Install fairseq2 using official source code, please note that the version used is v0.2.1

**Comment by QiushiStaff** [comment]
Has the big shot solved it yet?
