### ISSUE TITLE
[Finetune] Error(s) in loading state_dict for UnitYModel

### ISSUE THREAD

**Issue by muratozbek23** [facebookresearch/seamless_communication#350]
Hello everyone,

We want to train the data we have for speech to text. I explained the steps we did below. First, we adapted it to the data format. Then we finetuned it. After finetuning, we saved the weights.

Data example:
`{"source": {"id": 1, "lang": "tur", "text": "taksit market", "audio_local_path": "bizimSesler/taksit_market.wav", "waveform": null, "sampling_rate": 16000, "units": null}, "target": {"id": 1, "lang": "tur", "text": "taksit market", "audio_local_path": "bizimSesler/taksit_market.wav", "waveform": null, "sampling_rate": 16000, "units": null}}`

The prepared data in the 1st step was stored in train.json and test.json

The command we used while finetuning:
```
m4t_finetune
--mode SPEECH_TO_TEXT
--train_dataset train_data/train.json
--eval_dataset train_data/test.json
--learning_rate 1e-6
--warmup_steps 1000
--eval_steps 5000
--max_epochs 10
--patience 100
--batch_size 1
--model_name seamlessM4T_medium 
--save_model_to train_data/checkpoint.pt
```

After finishing finetune, I moved the weights to the predict file. 
The code has been revized to load the finetuned model:

i added this code to [here](https://github.com/facebookresearch/seamless_communication/blob/main/src/seamless_communication/cli/m4t/predict/predict.py#L208)
`translator.model.load_state_dict(torch.load("/train_data/checkpoint.pt"))
`
I tested with this command
`m4t_predict try.wav --task asr --tgt_lang "tur" --model_name seamlessM4T_medium
`

When I want to test the finetuned model, I constantly get this error.

```
Using the cached checkpoint of seamlessM4T_medium. Set `force` to `True` to download again.
Using the cached tokenizer of seamlessM4T_medium. Set `force` to `True` to download again.
Using the cached checkpoint of vocoder_36langs. Set `force` to `True` to download again.
/home/pantheon/.local/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/pantheon/Projects/muratCalismalari/S2T/seamlessV3/seamless_communication/src/seamless_communication/cli/m4t/predict/elle.py", line 7, in <module>
    translator.model.load_state_dict(torch.load("train_data/checkpoint.pt"))
  File "/home/pantheon/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnitYModel:
  Missing key(s) in state_dict: "text_encoder.layers.0.self_attn_layer_norm.weight", "text_encoder.layers.0.self_attn_layer_norm.bias", "text_encoder.layers.0.self_attn.q_proj.weight", "text_encoder.layers.0.self_attn.q_proj.bias", "text_encoder.layers.0.self_attn.k_proj.weight", "text_encoder.layers.0.self_attn.k_proj.bias", "text_encoder.layers.0.self_attn.v_proj.weight", "text_encoder.layers.0.self_attn.v_proj.bias", 
...
```
When I look at the names of the weights before and after finetuning, there is a clear difference. How can I solve it without changing the names one by one?

What am I doing wrong?

**Comment by developeranalyser** [comment]
you found  right way ?

**Comment by cageyoko** [comment]
Hi, have you checked the finetuned checkpoint weight? whether the weight speech-realated changed?

**Comment by muratozbek23** [comment]
i found a solution

you need to change values to None and after load a checkpoint

```
translator = Translator(args.model_name, args.vocoder_name, device, dtype=dtype)
translator.model.text_encoder = None
translator.model.t2u_model = None

translator.model.load_state_dict(torch.load("train_data/checkpoint_large.pt"))
```

**Comment by WandererGuy** [comment]
thank you , this is my solution now 
```
import torch
from seamless_communication.inference import Translator

saved_finetune_ckpt_path = "m4t_dataset_vie_asr/checkpoint.pt"
finetuned_checkpoint = torch.load(saved_finetune_ckpt_path)["model"]
model_name = torch.load(saved_finetune_ckpt_path)["model_name"]
vocoder_name = "vocoder_v2" if model_name == "seamlessM4T_v2_large" else "vocoder_36langs"

translator = Translator(
    model_name,
    vocoder_name,
    device=torch.device("cuda:0"),
    dtype=torch.float16 
)

# this 2 line only applies for SPEECH TO TEXT , see main function ịn src/seamless_communication/cli/m4t/finetune/finetune.py to see 
translator.model.text_encoder = None
translator.model.t2u_model = None

model_dict = translator.model.state_dict()
translator.model.load_state_dict(finetuned_checkpoint, strict=False)

path_to_input_audio = "finetune_dataset/wav_files/967f4bd2-7864-4e98-9eb3-9c7e20f8385b.wav"
tgt_lang = "vie"
# S2TT
text_output, _ = translator.predict(
    input=path_to_input_audio,
    task_str="S2TT",
    tgt_lang=tgt_lang
)
print (text_output[0])
# ASR
# This is equivalent to S2TT with `<tgt_lang>=<src_lang>`.
text_output, _ = translator.predict(
    input=path_to_input_audio,
    task_str="ASR",
    tgt_lang=tgt_lang
)
print (text_output[0])
```
