### ISSUE TITLE
Convenient to input data .tsv in speech recognition

### ISSUE THREAD

**Issue by wangsang123** [facebookresearch/seamless_communication#368]
ValueError: The input data does not have an element at path 'audio'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wangsang/.local/bin/streaming_evaluate", line 8, in <module>
    sys.exit(main())
  File "/home/wangsang/.local/lib/python3.8/site-packages/seamless_communication/cli/streaming/evaluate.py", line 100, in main
    evaluate(agent_class, {**base_config, **model_configs, **eval_configs}, parser)
  File "/home/wangsang/.local/lib/python3.8/site-packages/simuleval/cli.py", line 82, in evaluate
    evaluator(system)
  File "/home/wangsang/.local/lib/python3.8/site-packages/simuleval/evaluator/evaluator.py", line 249, in __call__
    for sample in self.iterator:
  File "/home/wangsang/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/wangsang/.local/lib/python3.8/site-packages/seamless_communication/streaming/dataloaders/s2tt.py", line 113, in __next__
    self.item = next(self.data_itr)
fairseq2.data.data_pipeline.DataPipelineError: The map operation has failed. See nested exception for details.

**Comment by TangLinJie** [comment]
I meet the same error:
ValueError: The input data does not have an element at path 'audio'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ljtang/miniconda3/bin/streaming_evaluate", line 8, in <module>
    sys.exit(main())
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/seamless_communication/cli/streaming/evaluate.py", line 100, in main
    evaluate(agent_class, {**base_config, **model_configs, **eval_configs}, parser)
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/simuleval/cli.py", line 82, in evaluate
    evaluator(system)
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/simuleval/evaluator/evaluator.py", line 249, in __call__
    for sample in self.iterator:
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/seamless_communication/streaming/dataloaders/s2tt.py", line 116, in __next__
    self.item = next(self.data_itr)
fairseq2.data.data_pipeline.DataPipelineError: The map operation has failed. See nested exception for details.

**Comment by lishaojun412** [comment]
> ValueError: The input data does not have an element at path 'audio'.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/wangsang/.local/bin/streaming_evaluate", line 8, in sys.exit(main()) File "/home/wangsang/.local/lib/python3.8/site-packages/seamless_communication/cli/streaming/evaluate.py", line 100, in main evaluate(agent_class, {**base_config, **model_configs, **eval_configs}, parser) File "/home/wangsang/.local/lib/python3.8/site-packages/simuleval/cli.py", line 82, in evaluate evaluator(system) File "/home/wangsang/.local/lib/python3.8/site-packages/simuleval/evaluator/evaluator.py", line 249, in **call** for sample in self.iterator: File "/home/wangsang/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in **iter** for obj in iterable: File "/home/wangsang/.local/lib/python3.8/site-packages/seamless_communication/streaming/dataloaders/s2tt.py", line 113, in **next** self.item = next(self.data_itr) fairseq2.data.data_pipeline.DataPipelineError: The map operation has failed. See nested exception for details.

Is it resolved?

**Comment by aranemini** [comment]
I faced the same error in speech to text translation. 

ValueError: The input data does not have an element at path 'audio'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mmoham/anaconda3/envs/traduction/bin/streaming_evaluate", line 8, in <module>
    sys.exit(main())
  File "/home/mmoham/anaconda3/envs/traduction/lib/python3.9/site-packages/seamless_communication/cli/streaming/evaluate.py", line 99, in main
    evaluate(agent_class, {**base_config, **model_configs, **eval_configs}, parser)
  File "/home/mmoham/anaconda3/envs/traduction/lib/python3.9/site-packages/simuleval/cli.py", line 82, in evaluate
    evaluator(system)
  File "/home/mmoham/anaconda3/envs/traduction/lib/python3.9/site-packages/simuleval/evaluator/evaluator.py", line 249, in __call__
    for sample in self.iterator:
  File "/home/mmoham/anaconda3/envs/traduction/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/mmoham/anaconda3/envs/traduction/lib/python3.9/site-packages/seamless_communication/streaming/dataloaders/s2tt.py", line 113, in __next__
    self.item = next(self.data_itr)
fairseq2.data.data_pipeline.DataPipelineError: The map operation has failed. See nested exception for details.

**Comment by aranemini** [comment]
In this line in  pipeline_builder.map(map_file, selector="audio") in s2tt file, "audio" is the name of relative address of the text files. You should have a header in the data.tsv file and put the name of audio file address "audio". 

> id	audio   txt1 spkid	  gender
> 1829	7105431834829365765.wav	Les voyageurs à destination de pays	150720	FEMALE

**Comment by StormVera** [comment]
I added a row in front of the five columns you mentioned in the tsv file and set the table headers you mentioned (at the same time, I deleted the two columns without column names), and the following problem appeared:

ValueError: The number of fields must match the number of names (7), but is 5 instead.

Has anyone encountered this problem? How did you solve it? Thank you
