### ISSUE TITLE
Streaming run error

### ISSUE THREAD

**Issue by zhhl9101** [facebookresearch/seamless_communication#384]
Using the cached tokenizer of seamless_streaming_unity. Set `force` to `True` to download again.
Using the cached tokenizer of seamless_streaming_unity. Set `force` to `True` to download again.
2024-03-13 07:41:57,500 INFO -- seamless_communication.streaming.agents.unity_pipeline: Loading the UnitY model: seamless_streaming_unity on device=cuda:0, dtype=torch.float16
Using the cached checkpoint of seamless_streaming_unity. Set `force` to `True` to download again.
2024-03-13 07:42:01,772 INFO -- seamless_communication.streaming.agents.unity_pipeline: Loading the Monotonic Decoder model: seamless_streaming_monotonic_decoder on device=cuda:0, dtype=torch.float16
Using the cached checkpoint of seamless_streaming_monotonic_decoder. Set `force` to `True` to download again.
2024-03-13 07:42:05,166 INFO -- simuleval.utils.agent: System will run on device: cuda:0. dtype: fp16
2024-03-13 07:42:05,166 INFO -- simuleval.dataloader: Evaluating from dataloader fairseq2_s2tt.
2024-03-13 07:42:05,166 WARNING -- seamless_communication.streaming.dataloaders.s2tt: Stripping silence in the beginning and the end of audio with SileroVAD.
Using cache found in /home/.cache/torch/hub/snakers4_silero-vad_master
Traceback (most recent call last):
  File "/data/env/m4t/bin/streaming_evaluate", line 8, in <module>
    sys.exit(main())
  File "/data/env/m4t/lib/python3.10/site-packages/seamless_communication/cli/streaming/evaluate.py", line 100, in main
    evaluate(agent_class, {**base_config, **model_configs, **eval_configs}, parser)
  File "/data/env/m4t/lib/python3.10/site-packages/simuleval/cli.py", line 80, in evaluate
    evaluator = build_evaluator(args)
  File "/data/env/m4t/lib/python3.10/site-packages/simuleval/evaluator/__init__.py", line 12, in build_evaluator
    return SentenceLevelEvaluator.from_args(args)
  File "/data/env/m4t/lib/python3.10/site-packages/simuleval/evaluator/evaluator.py", line 298, in from_args
    return cls(dataloader, quality_scorers, latency_scorers, args)
  File "/data/env/m4t/lib/python3.10/site-packages/simuleval/evaluator/evaluator.py", line 90, in __init__
    assert IS_IMPORT_SPM
AssertionError

**Comment by TangLinJie** [comment]
hello，i meet the same error，please tell me how to solve it

**Comment by zhhl9101** [comment]
> hello，i meet the same error，please tell me how to solve it

pip install sentencepiece

**Comment by TangLinJie** [comment]
please tell me your command and used dataset, thanks 

I use cvss-c ja dataset, running command 'streaming_evaluate --task s2tt --data-file ./cvssc_ja/test.tsv --audio-root-dir ./cvssc_ja/test --output ./test --tgt-lang eng --dtype fp32', but I get error log:
/home/ljtang/miniconda3/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Using the cached tokenizer of seamless_streaming_unity. Set `force` to `True` to download again.
Using the cached tokenizer of seamless_streaming_unity. Set `force` to `True` to download again.
2024-03-15 11:09:20,949 INFO -- seamless_communication.streaming.agents.unity_pipeline: Loading the UnitY model: seamless_streaming_unity on device=cuda:0, dtype=torch.float32
<class 'NoneType'>
<class 'seamless_communication.models.unity.model.UnitYModel'>
2024-03-15 11:09:22,196 INFO -- seamless_communication.streaming.agents.unity_pipeline: Loading the Monotonic Decoder model: seamless_streaming_monotonic_decoder on device=cuda:0, dtype=torch.float32
<class 'fairseq2.models.transformer.frontend.TransformerEmbeddingFrontend'>
1024
<class 'seamless_communication.models.monotonic_decoder.model.MonotonicDecoderModel'>
[OnlineFeatureExtractorAgent[speech -> speech], OfflineWav2VecBertEncoderAgent[speech -> speech], MMASpeechToTextDecoderAgent[speech -> text]]
2024-03-15 11:09:23,657 INFO -- simuleval.utils.agent: System will run on device: cuda:0. dtype: fp32
2024-03-15 11:09:23,657 INFO -- simuleval.dataloader: Evaluating from dataloader fairseq2_s2tt.
<fairseq2.data.data_pipeline.FileMapper object at 0x7f17cc07b430>
<fairseq2.data.data_pipeline.DataPipelineBuilder object at 0x7f17cc0f27b0>
2024-03-15 11:09:23,657 WARNING -- seamless_communication.streaming.dataloaders.s2tt: Stripping silence in the beginning and the end of audio with SileroVAD.
Using cache found in /home/ljtang/.cache/torch/hub/snakers4_silero-vad_master
  0%|                                                                                                                                                                          | 0/683 [00:00<?, ?it/s]<class 'fairseq2.data.data_pipeline.DataPipeline'>
<fairseq2.data.data_pipeline.DataPipeline object at 0x7f17cc07b470>
683
  0%|                                                                                                                                                                          | 0/683 [00:00<?, ?it/s]
ValueError: The input data does not have an element at path 'audio'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ljtang/miniconda3/bin/streaming_evaluate", line 8, in <module>
    sys.exit(main())
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/seamless_communication/cli/streaming/evaluate.py", line 100, in main
    evaluate(agent_class, {**base_config, **model_configs, **eval_configs}, parser)
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/simuleval/cli.py", line 82, in evaluate
    evaluator(system)
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/simuleval/evaluator/evaluator.py", line 249, in __call__
    for sample in self.iterator:
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/ljtang/miniconda3/lib/python3.10/site-packages/seamless_communication/streaming/dataloaders/s2tt.py", line 116, in __next__
    self.item = next(self.data_itr)
fairseq2.data.data_pipeline.DataPipelineError: The map operation has failed. See nested exception for details.
