### ISSUE TITLE
libsndfile Error 

### ISSUE THREAD

**Issue by gusanmaz** [facebookresearch/seamless_communication#42]
I first cloned the repo and then created a conda environment. 

Afterwards I ran following two commands as stated in Installation Section:

`pip install .`
`conda install -y -c conda-forge libsndfile`

Installation completes without and error. However if I run following code:

```bash
python3 scripts/m4t/predict/predict.py "Teknolojiyi merkezine alan yenilikçi yapımızla hayatını kolaylaştırmaya devam ediyoruz." t2tt en --src_lang tr
```

I get following output:

```
Traceback (most recent call last):
  File "/home/guvenc/seamless_communication/scripts/m4t/predict/predict.py", line 10, in <module>
    from seamless_communication.models.inference import Translator
  File "/home/guvenc/.local/lib/python3.10/site-packages/seamless_communication/models/inference/__init__.py", line 6, in <module>
    from seamless_communication.models.inference.translator import Translator as Translator
  File "/home/guvenc/.local/lib/python3.10/site-packages/seamless_communication/models/inference/translator.py", line 12, in <module>
    from fairseq2.data import Collater
  File "/home/guvenc/.local/lib/python3.10/site-packages/fairseq2/data/__init__.py", line 7, in <module>
    from fairseq2.data.cstring import CString as CString
  File "/home/guvenc/.local/lib/python3.10/site-packages/fairseq2/data/cstring.py", line 58, in <module>
    from fairseq2n.bindings.data.string import CString as CString
  File "/home/guvenc/.local/lib/python3.10/site-packages/fairseq2n/__init__.py", line 90, in <module>
    _load_sndfile()
  File "/home/guvenc/.local/lib/python3.10/site-packages/fairseq2n/__init__.py", line 80, in _load_sndfile
    raise OSError(
OSError: libsndfile is not found!. Use your system package manager to install it (e.g. `apt install libsndfile1`).
```

I use Ubuntu based Pop!_OS. 

`sudo apt install libsndfile1` outputs:

```bash
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libsndfile1 is already the newest version (1.0.31-2build1).
The following packages were automatically installed and are no longer required:
  golang-1.18-go golang-1.18-src golang-src
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 250 not upgraded.
```

Installing libsndfile (https://github.com/libsndfile/libsndfile) from source didn't help either.

I wonder what I might be doing wrong. 
Thanks!

**Comment by ChrisShaoMeng** [comment]
+1 Same error.

**Comment by cbalioglu** [comment]
@gusanmaz if you have been able to install libsndfile via your system package manager, could you please try to install seamless_communication in a regular Python virtual environment (i.e. no Conda)?

**Comment by ChrisShaoMeng** [comment]
> @gusanmaz if you have been able to install libsndfile via your system package manager, could you please try to install seamless_communication in a regular Python virtual environment (i.e. no Conda)?

It works for me, thanks!

**Comment by cgalisteo-stratio** [comment]
> @gusanmaz if you have been able to install libsndfile via your system package manager, could you please try to install seamless_communication in a regular Python virtual environment (i.e. no Conda)?

That was the solution for me. I was getting that error using a conda environment, but now it's working with a regular virtualenv.

**Comment by gusanmaz** [comment]
Thank you for the advice @cbalioglu.  

This time I am getting `ERROR: Could not find a version that satisfies the requirement fairseq2n==0.1.0 (from fairseq2) (from versions: none)
ERROR: No matching distribution found for fairseq2n==0.1.0` message during installation.  It appears like same issue has already been reported under fairseq2 issues: https://github.com/facebookresearch/fairseq2/issues/1 .

I am able to install and run seamless_communication without using conda environment on my another less powerful machine with same OS with no libsndfile error.  I am getting CUDA out of memory error.  This machine has only 4GB vram whereas the other one has 12GB vram.

**Comment by gusanmaz** [comment]
I solved the problem. It now works in 12GB vram machine with big model and 4GB vram machine with medium model.

**Comment by cbalioglu** [comment]
@gusanmaz glad to hear! Closing this issue. Let us know if you experience another problem.

**Comment by milo157** [comment]
Hi @cbalioglu @jborut 

It seems the issue still occurs in conda environments. Doing apt install worked for me however my entire application env is in conda so I am not sure how to link conda and apt installs and if you even can?

**Comment by shashank-neuralgarage** [comment]
> I solved the problem. It now works in 12GB vram machine with big model and 4GB vram machine with medium model.

Can you share what worked for you?
