### ISSUE TITLE
[help]  libsndfile is not found | mac m1 proMax, sonoma14.4

### ISSUE THREAD

**Issue by OpenSourceCommunityInterface** [facebookresearch/seamless_communication#475]
(base) ➜  seamless_communication git:(main) ✗ m4t_predict ./input/test.mp3 --task s2st --tgt_lang fra --output_path ./output
Traceback (most recent call last):
  File "/opt/homebrew/bin/m4t_predict", line 5, in <module>
    from seamless_communication.cli.m4t.predict.predict import main
  File "/opt/homebrew/lib/python3.9/site-packages/seamless_communication/__init__.py", line 9, in <module>
    from fairseq2.assets import FileAssetMetadataProvider, asset_store
  File "/opt/homebrew/lib/python3.9/site-packages/fairseq2/__init__.py", line 9, in <module>
    import fairseq2n
  File "/opt/homebrew/lib/python3.9/site-packages/fairseq2n/__init__.py", line 110, in <module>
    _load_shared_libraries()
  File "/opt/homebrew/lib/python3.9/site-packages/fairseq2n/__init__.py", line 33, in _load_shared_libraries
    _load_sndfile()
  File "/opt/homebrew/lib/python3.9/site-packages/fairseq2n/__init__.py", line 58, in _load_sndfile
    raise OSError(
OSError: libsndfile is not found! Since you are in a Conda environment, use `conda install -c conda-forge libsndfile==1.0.31` to install it.

**Comment by OpenSourceCommunityInterface** [comment]
have no idea about this,  can help?

**Comment by cesarvspr** [comment]
same here
