### ISSUE TITLE
about tsv file

### ISSUE THREAD

**Issue by sunyclj** [facebookresearch/seamless_communication#492]
command: streaming_evaluate --task s2st --data-file ../audio-tsv/test.tsv --audio-root-dir ../test_data/audio/ --output ../ --tgt-lang eng --no-scoring
2024-07-11 05:44:48,463 INFO -- seamless_communication.streaming.agents.unity_pipeline: Loading the UnitY model: seamless_streaming_unity on device=cuda:0, dtype=torch.float16
2024-07-11 05:44:56,398 INFO -- seamless_communication.streaming.agents.unity_pipeline: Loading the Monotonic Decoder model: seamless_streaming_monotonic_decoder on device=cuda:0, dtype=torch.float16
2024-07-11 05:45:02,766 INFO -- seamless_communication.streaming.agents.online_vocoder: Loading the Vocoder model: vocoder_v2 on device=cuda:0, dtype=torch.float16
/opt/conda/envs/smlss_server/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
2024-07-11 05:45:05,959 INFO -- simuleval.utils.agent: System will run on device: cuda:0. dtype: fp16
2024-07-11 05:45:05,959 INFO -- simuleval.dataloader: Evaluating from dataloader fairseq2_s2tt.
2024-07-11 05:45:05,963 WARNING -- seamless_communication.streaming.dataloaders.s2tt: Stripping silence in the beginning and the end of audio with SileroVAD.
Using cache found in /home/jovyan/.cache/torch/hub/snakers4_silero-vad_master
Traceback (most recent call last):
  File "/opt/conda/envs/smlss_server/bin/streaming_evaluate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/smlss_server/lib/python3.8/site-packages/seamless_communication/cli/streaming/evaluate.py", line 100, in main
    evaluate(agent_class, {**base_config, **model_configs, **eval_configs}, parser)
  File "/opt/conda/envs/smlss_server/lib/python3.8/site-packages/simuleval/cli.py", line 80, in evaluate
    evaluator = build_evaluator(args)
  File "/opt/conda/envs/smlss_server/lib/python3.8/site-packages/simuleval/evaluator/__init__.py", line 12, in build_evaluator
    return SentenceLevelEvaluator.from_args(args)
  File "/opt/conda/envs/smlss_server/lib/python3.8/site-packages/simuleval/evaluator/evaluator.py", line 298, in from_args
    return cls(dataloader, quality_scorers, latency_scorers, args)
  File "/opt/conda/envs/smlss_server/lib/python3.8/site-packages/simuleval/evaluator/evaluator.py", line 141, in __init__
    self.end_index = len(self.dataloader)
ValueError: __len__() should return >= 0

**Comment by sunyclj** [comment]
![image](https://github.com/facebookresearch/seamless_communication/assets/44860428/fce4c8c0-04a3-4e2e-98e0-e32189fc8059)
已解决

**Comment by StormVera** [comment]
你好，请问你使用的test.tsv是什么形式的？可以截图看一下吗？另外，请问你通过streaming_evaluate得到的最终的结果怎样？（因为我使用fleurs其中的en_us数据集，tgt_lang=cmn，最终得到的结果似乎并不太好），应该对得到的结果怎么进行评价呢？
