### ISSUE TITLE
I would like to improve MT translation layer to handle context of discussion

### ISSUE THREAD

**Issue by cyberluke** [facebookresearch/seamless_communication#517]
Hello, current translation for S2S produces very low precision.

I am interested in Czech and Vietnamese translation.

If I say: "Today is cold" it will incorrectly translate as "big winter" instead of "cold". In Vietnamese: "mùa đông lớn" while correct term is "lạnh".

**1) Is it possible to replace your MT layer by something else?**

Next, I would like to implement some rule-based or phrase-based post processing according to context.

**2) Translation produces disrepectful output**
For example if I say in previous prompt: "mẹ ơi" to ask mom, I want to save this information in some user context and then when I mention "me" in next conversation it must not output "tôi", but it must replace this word by "con" which means child.

It is very high disrespect to use word "tôi" on parents. So this use might fall into ethical use of AI as well.

Could you recommend some approach how to accomplis that?

I think the right place to do it is here:
https://github.com/facebookresearch/seamless_communication/blob/main/src/seamless_communication/inference/translator.py

I'm also thinking that it would be better to translate Czech to English first and then English to Vietnamese and then synthetise the speech.

**Comment by deepak-kumar-98** [comment]
Hi @cyberluke , can you pls share the sample of dataset which you are processing as i am getting below error:

Traceback (most recent call last):
  File "/Users/deepakkumar/Documents/seamless/venv/bin/m4t_finetune", line 33, in <module>
    sys.exit(load_entry_point('seamless-communication', 'console_scripts', 'm4t_finetune')())
  File "/Users/deepakkumar/Documents/seamless/seamless_communication/src/seamless_communication/cli/m4t/finetune/finetune.py", line 217, in main
    finetune.run()
  File "/Users/deepakkumar/Documents/seamless/seamless_communication/src/seamless_communication/cli/m4t/finetune/trainer.py", line 411, in run
    self._eval_model(n_batches=100)
  File "/Users/deepakkumar/Documents/seamless/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/deepakkumar/Documents/seamless/seamless_communication/src/seamless_communication/cli/m4t/finetune/trainer.py", line 351, in _eval_model
    loss = self.calc_loss(batch, *self.model(batch))
  File "/Users/deepakkumar/Documents/seamless/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/deepakkumar/Documents/seamless/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/deepakkumar/Documents/seamless/seamless_communication/src/seamless_communication/cli/m4t/finetune/trainer.py", line 127, in forward
    assert batch.text_to_units.prev_output_tokens is not None
AssertionError
