### ISSUE TITLE
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wahahaer** [facebookresearch/seamless_communication#72]
OS: ubuntu 18.04
Python: 3.9
PyTorch: 2.0.1+cu117

Installation as follow sucessfully.
```
pip install .
conda install -y -c conda-forge libsndfile
```
run with error:
```
m4t_predict <input_text> t2tt <tgt_lang> --src_lang <src_lang>
```

Traceback (most recent call last):
  File "/data/seamless_communication/build/lib/m4t_scripts/predict/predict.py", line 9, in <module>
    import torchaudio
  File "/home/ai/anaconda3/envs/cpm39/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/ai/anaconda3/envs/cpm39/lib/python3.9/site-packages/torchaudio/_extension.py", line 135, in <module>
    _init_extension()
  File "/home/ai/anaconda3/envs/cpm39/lib/python3.9/site-packages/torchaudio/_extension.py", line 105, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/ai/anaconda3/envs/cpm39/lib/python3.9/site-packages/torchaudio/_extension.py", line 52, in _load_lib
    torch.ops.load_library(path)
  File "/home/ai/anaconda3/envs/cpm39/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/ai/anaconda3/envs/cpm39/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory

**Comment by cndn** [comment]
Hey @wahahaer Could you double check your torchaudio version? It needs to match pytorch version. Reinstalling torchaudio==2.0.1 might resolve the issue in your case.

**Comment by wahahaer** [comment]
> Hey @wahahaer Could you double check your torchaudio version? It needs to match pytorch version. Reinstalling torchaudio==2.0.1 might resolve the issue in your case.

thanks, u are right.
I have solved the problem as your suggestion.
