### ISSUE TITLE
ValueError: The input sequence length must be less than or equal to the maximum sequence length (1024), but is 1228 instead.

### ISSUE THREAD

**Issue by kk3dmax** [facebookresearch/seamless_communication#90]
ValueError: The input sequence length must be less than or equal to the maximum sequence length (1024), but is 1228 instead.

Code:
translated_text, _, _ = translator.predict(text, "t2tt", 'cmn', src_lang='eng')

Why default max seq len is 1024 not 4096? How can I change it to 4096?

**Comment by kk3dmax** [comment]
I found this --> (pos_encoder): SinusoidalPositionEncoder(encoding_dim=1024, max_seq_len=1024).

How can I change it to 4096?

**Comment by kk3dmax** [comment]
Traceback (most recent call last):
  File "/home/dell/try_code/try_m4t.py", line 21, in <module>
    translated_text, _, _ = translator.predict(text, "t2tt", 'cmn', src_lang='eng')
  File "/home/dell/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/seamless_communication/models/inference/translator.py", line 210, in predict
    result = self.get_prediction(
  File "/home/dell/miniconda3/lib/python3.10/site-packages/seamless_communication/models/inference/translator.py", line 130, in get_prediction
    return generator(
  File "/home/dell/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/seamless_communication/models/unity/generator.py", line 175, in __call__
    text_output = self.t2t_generator.generate_ex(source_seqs, source_seq_lens)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/fairseq2/generation/text.py", line 155, in generate_ex
    return self._do_generate(source_seqs, source_seq_lens)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/fairseq2/generation/text.py", line 71, in _do_generate
    encoder_output, encoder_padding_mask = self.model.encode(
  File "/home/dell/miniconda3/lib/python3.10/site-packages/seamless_communication/models/unity/model.py", line 190, in encode
    seqs, padding_mask = self.encoder_frontend(seqs, seq_lens)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/fairseq2/models/transformer/frontend.py", line 158, in forward
    embeds = self.pos_encoder(embeds, padding_mask, state_bag)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/fairseq2/nn/position_encoder.py", line 75, in forward
    return self._do_forward(seqs, padding_mask, state_bag)
  File "/home/dell/miniconda3/lib/python3.10/site-packages/fairseq2/nn/position_encoder.py", line 245, in _do_forward
    return seqs + self.weight[start_step : start_step + seq_len]
RuntimeError: The size of tensor a (1228) must match the size of tensor b (1024) at non-singleton dimension 1

After change the max_seq_len from 1024 to 4096 (with below codes), I got above error.
translator._modules['model'].text_encoder_frontend.pos_encoder.max_seq_len = 4096
translator._modules['model'].text_decoder_frontend.pos_encoder.max_seq_len = 4096

Is there a way to extend t2tt max input token length from 1024 to 4096?

**Comment by danieljose** [comment]
This translator is not really intended for large chunks of text. It is better to divide it. For example to translate a text file: 

#https://github.com/facebookresearch/seamless_communication/issues/98

**Comment by cbalioglu** [comment]
@kk3dmax please check out @danieljose's answer. You can force the model to accept longer sequence lengths by setting the `max_seq_len` attribute in [model configuration](https://github.com/facebookresearch/fairseq2/blob/main/src/fairseq2/models/nllb/builder.py#L88), but since NLLB uses fixed sinusoidal positional encoder, most likely longer sequence lengths will cause a (significant) drop in model accuracy. I also suggest splitting your input into chunks. Closing this issue for now, but feel free to re-open it if you have further questions.
